### PR TITLE
Chapter 10: Fix Place.name to delegated constraint

### LINKED ISSUE #53: Chapter 10: UnsupportedFeatureError in upsert example
```
INSERT City {
  name := 'Munich',
  population := 123456,
} UNLESS CONFLICT ON .name
ELSE (
  UPDATE City
  SET {
    population := 123456,
  }
);
```

This example leads to the following: `error: UnsupportedFeatureError: UNLESS CONFLICT can not use ELSE when constraint is from a parent type`. 

Not sure if it should be a different example, or if there is some way to express this in a supported way.  The code for this error has a TODO saying it should be supported.

### PR DESCRIPTION
**Pull request by vladpi**
Fixes #53

### CODE REVIEW

**Review by 1st1 — APPROVED** [review]

**Comment by 1st1** [comment]
cc @daichen-daisy

**Comment by vladpi** [comment]
@1st1 @vpetrovykh Thought just now, should I fix this in all the following chapters?

**Comment by daichen-daisy** [comment]
@1st1 Thanks for reminding me. I noticed. I will give an eye on the master in the future. Once there is a new commit in the master, I will create a new pull request to sync the Chinese version. Do you think this workflow is OK for the team?

**Comment by daichen-daisy** [comment]
> @1st1 @vpetrovykh Thought just now, should I fix this in all the following chapters?

@vladpi Your commit has been merged to master, so I guess you can fix this in other related places? or If you don't have time, I can do it instead of you. Thanks anyway.

**Comment by vladpi** [comment]
> > @1st1 @vpetrovykh Thought just now, should I fix this in all the following chapters?
> 
> @vladpi Your commit has been merged to master, so I guess you can fix this in other related places? or If you don't have time, I can do it instead of you. Thanks anyway.

@daichen-daisy Yeah, let me fix it

**Pull request merged**
